### ISSUE TITLE
VIES url asks for member state

### ISSUE THREAD

**Issue by lfolco** [sandermangel/rkvatfallback#2]
It seems that the first fallback for VIES doesn't take ISO as a query parameter for country. if you put in the following URL you'll see a validation message: "Please first select a Member State"

http://ec.europa.eu/taxation_customs/vies/viesquer.do?ms=&iso=IT&vat=02330191202&BtnSubmitVat=Verify

Wasn't sure where to find the names of the query parameters.

**Comment by peterjaap** [comment]
The 'ms' argument is the country code as well; http://ec.europa.eu/taxation_customs/vies/viesquer.do?ms=IT&iso=IT&vat=02330191202&BtnSubmitVat=Verify

**Comment by peterjaap** [comment]
@sandermangel can you close this one.
